### ISSUE TITLE
[gdi - chanext-fairdatapoint - SPIKE] What is the update strategy applied by the harvesters?

### ISSUE THREAD

**Issue by brunopacheco1** [GenomicDataInfrastructure/gdi-userportal-ckanext-fairdatapoint#19]
### 🎯 What? (Story Description)

We need to understand how the harvester handles duplication and updates.

### 💡 Why? (Justification)

So we don't have surprises or unexpected behaiour.

### 🔨 Tasks (Breakdown)

- Understand how Harvester handles duplication and what is the update strategy behind it.
- Document in `gdi-userportal-docs`.
- Create stories for fixing or improving, if needed.

### ✅ Acceptance Criteria

- Are the findings documented?
- Are there new stories to work on gaps or bugs?

**Comment by a-nayden** [comment]
During gather stage the harvester requests all the available guid from a source. Guids are generated as `catalog=<link to fdp catalog>;dataset=<link to fdp dataset>`
Then it queries database for guide harvested from the same source (that means datasets. will be considered different if you configure a harvester source, then delete it and then re-configure).
The query is 
```
SELECT harvest_object.guid AS harvest_object_guid, harvest_object.package_id AS harvest_object_package_id 
FROM harvest_object 
WHERE harvest_object.current = true AND harvest_object.harvest_source_id = %(harvest_source_id_1)s
```
where %(harvest_source_id_1)s is harvester source id of the current job.

based on these two lists of guids a harvest object is assigned with status "delete", "new" or "change".

**Comment by a-nayden** [comment]
Also as per documentation it is possible to avoid updating certain fields: https://github.com/ckan/ckanext-harvest?tab=readme-ov-file#avoid-overwriting-certain-fields-optional
